### ISSUE TITLE
Can I set properties with this?

### ISSUE THREAD

**Issue by albertsj1** [RubyOpenSource/zenoss_client#3]
Sorry to open an issue for a quesiton, but I wasn't sure how else to ask. 
Can i use this to set cproperties for a device?
Thanks
John

**Comment by skrobul** [comment]
@albertsj1  I realize that it's been almost 4 years, so I'm going to close this issue. I assume that [changes](https://github.com/RubyOpenSource/zenoss_client/compare/7893dcf1f1088ae795d220b51a7800538f5bfab1...4f7b50382e6497156101c7f1e3a825df1157768a) introduced back in Jun 2011 delivered this particular feature as expected. If that's not the case, please reopen.

**Comment by albertsj1** [comment]
Yes. I believe it worked as expected.  Thanks.
