### ISSUE TITLE
json runtime dependency

### ISSUE THREAD

**Issue by kaitea** [RubyOpenSource/zenoss_client#9]
Is there a reason why the json runtime dep. is set to 1.5?

Can it be set to >= 1.5 in the gemspec?

**Comment by bjmllr** [comment]
@kaitea Do you still have json 1.5 installed after running `bundle update json`? The current specification of `~> 1.5` should accept any version lower than 2.0. When I do a clean install, zenoss_client pulls in json 1.8.2, the latest as of this writing.

I'm running with httpclient 2.3.4.x so I'd like it if the `httpclient` dependency were modified as described here.

@zenchild I have access to a Zenoss instance, I can check out the unmerged PR branches and test them if that would be helpful.

**Comment by zenchild** [comment]
@bjmllr That would be great.

I'd love hand off support of this gem. You interested? Maybe I can create an org for it and add a few people to take over support. @dpetzel or @mindreframer you guys interested as well?

**Comment by bjmllr** [comment]
Wow, quick reply after 2 years. :)

I'm game to accept a hand off. If you make an org, @skrobul might be interested as well.

**Comment by zenchild** [comment]
Yeah, I've been a pretty bad open source citizen in recent times. I'm trying to get back on track again. I started an org for a few of my other gems and it's nice to have a team working on things instead of a solitary person. Shared energy for doing pull requests. :)

**Comment by bjmllr** [comment]
No worries, I have just come to expect communications to take days or weeks on github. I'm only starting out in being a good citizen these past few months after years of benefiting from others' work. You made a solid gem that I've gotten good use out, so I'll be proud if I can give back in some way.

**Comment by skrobul** [comment]
@zenchild If you decide to create an org, count me in as well please :)

**Comment by zenchild** [comment]
@skrobul You should receive an invite shortly....

**Comment by bjmllr** [comment]
@kaitea I'm going to close this issue, but please feel free to reopen and/or reply again if you are still having a problem.
